export enum CharState {
    Idle = 'Idle',
    Run = 'Run',
    Dash = 'Dash',
    Jump = 'Jump',
    UpToFall = 'UpToFall',
    Fall = 'Fall',
    Attack1 = 'Attack1',
    Attack2 = 'Attack2',
    Attack3 = 'Attack3',
    DashAttack = 'DashAttack',
    Blocking = 'Blocking',
    Slide = 'Slide',
    Stunned = 'Stunned',
    AirRun = 'AirRun',
}